package com.fastma.fastma.dao;

import com.fastma.fastma.entity.Betorder;
import com.fastma.fastma.entity.BetorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BetorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int countByExample(BetorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int deleteByExample(BetorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bet_orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int insert(Betorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int insertSelective(Betorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    List<Betorder> selectByExample(BetorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    Betorder selectByPrimaryKey(Integer bet_orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Betorder record, @Param("example") BetorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Betorder record, @Param("example") BetorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Betorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Betorder record);
}