package com.fastma.fastma.dao;

import com.fastma.fastma.entity.Game;
import com.fastma.fastma.entity.GameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int countByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int deleteByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int insertSelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    List<Game> selectByExample(GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Game record, @Param("example") GameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Game record, @Param("example") GameExample example);
}