package com.fastma.fastma.dao;

import com.fastma.fastma.entity.Racetrack;
import com.fastma.fastma.entity.RacetrackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RacetrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int countByExample(RacetrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int deleteByExample(RacetrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer racetrack_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int insert(Racetrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int insertSelective(Racetrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    List<Racetrack> selectByExample(RacetrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    Racetrack selectByPrimaryKey(Integer racetrack_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Racetrack record, @Param("example") RacetrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Racetrack record, @Param("example") RacetrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Racetrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table racetrack
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Racetrack record);
}