package com.fastma.fastma.dao;

import com.fastma.fastma.entity.Topup;
import com.fastma.fastma.entity.TopupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int countByExample(TopupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int deleteByExample(TopupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int insert(Topup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int insertSelective(Topup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    List<Topup> selectByExample(TopupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    Topup selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Topup record, @Param("example") TopupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Topup record, @Param("example") TopupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Topup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Topup record);
}