package com.fastma.fastma.dao;

import com.fastma.fastma.entity.TxidBackup;
import com.fastma.fastma.entity.TxidBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxidBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int countByExample(TxidBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int deleteByExample(TxidBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int insert(TxidBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int insertSelective(TxidBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    List<TxidBackup> selectByExample(TxidBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    TxidBackup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TxidBackup record, @Param("example") TxidBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TxidBackup record, @Param("example") TxidBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TxidBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table txid_backup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TxidBackup record);
}