package com.fastma.fastma.entity;

public class Game {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.iteration
     *
     * @mbggenerated
     */
    private Integer iteration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.total_volume
     *
     * @mbggenerated
     */
    private Integer total_volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.user_count
     *
     * @mbggenerated
     */
    private Integer user_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.racetrack_row
     *
     * @mbggenerated
     */
    private Integer racetrack_row;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game.is_betting
     *
     * @mbggenerated
     */
    private Integer is_betting;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.iteration
     *
     * @return the value of game.iteration
     *
     * @mbggenerated
     */
    public Integer getIteration() {
        return iteration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.iteration
     *
     * @param iteration the value for game.iteration
     *
     * @mbggenerated
     */
    public void setIteration(Integer iteration) {
        this.iteration = iteration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.total_volume
     *
     * @return the value of game.total_volume
     *
     * @mbggenerated
     */
    public Integer getTotal_volume() {
        return total_volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.total_volume
     *
     * @param total_volume the value for game.total_volume
     *
     * @mbggenerated
     */
    public void setTotal_volume(Integer total_volume) {
        this.total_volume = total_volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.user_count
     *
     * @return the value of game.user_count
     *
     * @mbggenerated
     */
    public Integer getUser_count() {
        return user_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.user_count
     *
     * @param user_count the value for game.user_count
     *
     * @mbggenerated
     */
    public void setUser_count(Integer user_count) {
        this.user_count = user_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.racetrack_row
     *
     * @return the value of game.racetrack_row
     *
     * @mbggenerated
     */
    public Integer getRacetrack_row() {
        return racetrack_row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.racetrack_row
     *
     * @param racetrack_row the value for game.racetrack_row
     *
     * @mbggenerated
     */
    public void setRacetrack_row(Integer racetrack_row) {
        this.racetrack_row = racetrack_row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game.is_betting
     *
     * @return the value of game.is_betting
     *
     * @mbggenerated
     */
    public Integer getIs_betting() {
        return is_betting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game.is_betting
     *
     * @param is_betting the value for game.is_betting
     *
     * @mbggenerated
     */
    public void setIs_betting(Integer is_betting) {
        this.is_betting = is_betting;
    }
}