package com.fastma.fastma.entity;

public class Racetrack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racetrack.racetrack_id
     *
     * @mbggenerated
     */
    private Integer racetrack_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racetrack.stake_token
     *
     * @mbggenerated
     */
    private Integer stake_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racetrack.race_distance
     *
     * @mbggenerated
     */
    private Integer race_distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racetrack.if_win
     *
     * @mbggenerated
     */
    private Integer if_win;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column racetrack.iteration
     *
     * @mbggenerated
     */
    private Integer iteration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racetrack.racetrack_id
     *
     * @return the value of racetrack.racetrack_id
     *
     * @mbggenerated
     */
    public Integer getRacetrack_id() {
        return racetrack_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racetrack.racetrack_id
     *
     * @param racetrack_id the value for racetrack.racetrack_id
     *
     * @mbggenerated
     */
    public void setRacetrack_id(Integer racetrack_id) {
        this.racetrack_id = racetrack_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racetrack.stake_token
     *
     * @return the value of racetrack.stake_token
     *
     * @mbggenerated
     */
    public Integer getStake_token() {
        return stake_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racetrack.stake_token
     *
     * @param stake_token the value for racetrack.stake_token
     *
     * @mbggenerated
     */
    public void setStake_token(Integer stake_token) {
        this.stake_token = stake_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racetrack.race_distance
     *
     * @return the value of racetrack.race_distance
     *
     * @mbggenerated
     */
    public Integer getRace_distance() {
        return race_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racetrack.race_distance
     *
     * @param race_distance the value for racetrack.race_distance
     *
     * @mbggenerated
     */
    public void setRace_distance(Integer race_distance) {
        this.race_distance = race_distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racetrack.if_win
     *
     * @return the value of racetrack.if_win
     *
     * @mbggenerated
     */
    public Integer getIf_win() {
        return if_win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racetrack.if_win
     *
     * @param if_win the value for racetrack.if_win
     *
     * @mbggenerated
     */
    public void setIf_win(Integer if_win) {
        this.if_win = if_win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column racetrack.iteration
     *
     * @return the value of racetrack.iteration
     *
     * @mbggenerated
     */
    public Integer getIteration() {
        return iteration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column racetrack.iteration
     *
     * @param iteration the value for racetrack.iteration
     *
     * @mbggenerated
     */
    public void setIteration(Integer iteration) {
        this.iteration = iteration;
    }
}