package com.fastma.fastma.entity;

public class Topup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.cb_id
     *
     * @mbggenerated
     */
    private String cb_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.order_size
     *
     * @mbggenerated
     */
    private Integer order_size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.if_done
     *
     * @mbggenerated
     */
    private Integer if_done;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.orderid
     *
     * @return the value of topup.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.orderid
     *
     * @param orderid the value for topup.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.cb_id
     *
     * @return the value of topup.cb_id
     *
     * @mbggenerated
     */
    public String getCb_id() {
        return cb_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.cb_id
     *
     * @param cb_id the value for topup.cb_id
     *
     * @mbggenerated
     */
    public void setCb_id(String cb_id) {
        this.cb_id = cb_id == null ? null : cb_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.order_size
     *
     * @return the value of topup.order_size
     *
     * @mbggenerated
     */
    public Integer getOrder_size() {
        return order_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.order_size
     *
     * @param order_size the value for topup.order_size
     *
     * @mbggenerated
     */
    public void setOrder_size(Integer order_size) {
        this.order_size = order_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.if_done
     *
     * @return the value of topup.if_done
     *
     * @mbggenerated
     */
    public Integer getIf_done() {
        return if_done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.if_done
     *
     * @param if_done the value for topup.if_done
     *
     * @mbggenerated
     */
    public void setIf_done(Integer if_done) {
        this.if_done = if_done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.userid
     *
     * @return the value of topup.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.userid
     *
     * @param userid the value for topup.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}