package com.fastma.fastma.entity;

import java.util.Date;

public class TxidBackup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txid_backup.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txid_backup.txid
     *
     * @mbggenerated
     */
    private String txid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txid_backup.selected
     *
     * @mbggenerated
     */
    private Integer selected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column txid_backup.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txid_backup.id
     *
     * @return the value of txid_backup.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txid_backup.id
     *
     * @param id the value for txid_backup.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txid_backup.txid
     *
     * @return the value of txid_backup.txid
     *
     * @mbggenerated
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txid_backup.txid
     *
     * @param txid the value for txid_backup.txid
     *
     * @mbggenerated
     */
    public void setTxid(String txid) {
        this.txid = txid == null ? null : txid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txid_backup.selected
     *
     * @return the value of txid_backup.selected
     *
     * @mbggenerated
     */
    public Integer getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txid_backup.selected
     *
     * @param selected the value for txid_backup.selected
     *
     * @mbggenerated
     */
    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column txid_backup.time
     *
     * @return the value of txid_backup.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column txid_backup.time
     *
     * @param time the value for txid_backup.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}