package com.fastma.fastma.entity;

import java.util.ArrayList;
import java.util.List;

public class WithdrawExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public WithdrawExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReq_idIsNull() {
            addCriterion("req_id is null");
            return (Criteria) this;
        }

        public Criteria andReq_idIsNotNull() {
            addCriterion("req_id is not null");
            return (Criteria) this;
        }

        public Criteria andReq_idEqualTo(Integer value) {
            addCriterion("req_id =", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idNotEqualTo(Integer value) {
            addCriterion("req_id <>", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idGreaterThan(Integer value) {
            addCriterion("req_id >", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("req_id >=", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idLessThan(Integer value) {
            addCriterion("req_id <", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idLessThanOrEqualTo(Integer value) {
            addCriterion("req_id <=", value, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idIn(List<Integer> values) {
            addCriterion("req_id in", values, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idNotIn(List<Integer> values) {
            addCriterion("req_id not in", values, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idBetween(Integer value1, Integer value2) {
            addCriterion("req_id between", value1, value2, "req_id");
            return (Criteria) this;
        }

        public Criteria andReq_idNotBetween(Integer value1, Integer value2) {
            addCriterion("req_id not between", value1, value2, "req_id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenIsNull() {
            addCriterion("amount_token is null");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenIsNotNull() {
            addCriterion("amount_token is not null");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenEqualTo(Double value) {
            addCriterion("amount_token =", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenNotEqualTo(Double value) {
            addCriterion("amount_token <>", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenGreaterThan(Double value) {
            addCriterion("amount_token >", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenGreaterThanOrEqualTo(Double value) {
            addCriterion("amount_token >=", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenLessThan(Double value) {
            addCriterion("amount_token <", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenLessThanOrEqualTo(Double value) {
            addCriterion("amount_token <=", value, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenIn(List<Double> values) {
            addCriterion("amount_token in", values, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenNotIn(List<Double> values) {
            addCriterion("amount_token not in", values, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenBetween(Double value1, Double value2) {
            addCriterion("amount_token between", value1, value2, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_tokenNotBetween(Double value1, Double value2) {
            addCriterion("amount_token not between", value1, value2, "amount_token");
            return (Criteria) this;
        }

        public Criteria andAmount_eosIsNull() {
            addCriterion("amount_eos is null");
            return (Criteria) this;
        }

        public Criteria andAmount_eosIsNotNull() {
            addCriterion("amount_eos is not null");
            return (Criteria) this;
        }

        public Criteria andAmount_eosEqualTo(Double value) {
            addCriterion("amount_eos =", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosNotEqualTo(Double value) {
            addCriterion("amount_eos <>", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosGreaterThan(Double value) {
            addCriterion("amount_eos >", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosGreaterThanOrEqualTo(Double value) {
            addCriterion("amount_eos >=", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosLessThan(Double value) {
            addCriterion("amount_eos <", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosLessThanOrEqualTo(Double value) {
            addCriterion("amount_eos <=", value, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosIn(List<Double> values) {
            addCriterion("amount_eos in", values, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosNotIn(List<Double> values) {
            addCriterion("amount_eos not in", values, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosBetween(Double value1, Double value2) {
            addCriterion("amount_eos between", value1, value2, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andAmount_eosNotBetween(Double value1, Double value2) {
            addCriterion("amount_eos not between", value1, value2, "amount_eos");
            return (Criteria) this;
        }

        public Criteria andIf_doneIsNull() {
            addCriterion("if_done is null");
            return (Criteria) this;
        }

        public Criteria andIf_doneIsNotNull() {
            addCriterion("if_done is not null");
            return (Criteria) this;
        }

        public Criteria andIf_doneEqualTo(Integer value) {
            addCriterion("if_done =", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneNotEqualTo(Integer value) {
            addCriterion("if_done <>", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneGreaterThan(Integer value) {
            addCriterion("if_done >", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneGreaterThanOrEqualTo(Integer value) {
            addCriterion("if_done >=", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneLessThan(Integer value) {
            addCriterion("if_done <", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneLessThanOrEqualTo(Integer value) {
            addCriterion("if_done <=", value, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneIn(List<Integer> values) {
            addCriterion("if_done in", values, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneNotIn(List<Integer> values) {
            addCriterion("if_done not in", values, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneBetween(Integer value1, Integer value2) {
            addCriterion("if_done between", value1, value2, "if_done");
            return (Criteria) this;
        }

        public Criteria andIf_doneNotBetween(Integer value1, Integer value2) {
            addCriterion("if_done not between", value1, value2, "if_done");
            return (Criteria) this;
        }

        public Criteria andEos_accountIsNull() {
            addCriterion("eos_account is null");
            return (Criteria) this;
        }

        public Criteria andEos_accountIsNotNull() {
            addCriterion("eos_account is not null");
            return (Criteria) this;
        }

        public Criteria andEos_accountEqualTo(String value) {
            addCriterion("eos_account =", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountNotEqualTo(String value) {
            addCriterion("eos_account <>", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountGreaterThan(String value) {
            addCriterion("eos_account >", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountGreaterThanOrEqualTo(String value) {
            addCriterion("eos_account >=", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountLessThan(String value) {
            addCriterion("eos_account <", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountLessThanOrEqualTo(String value) {
            addCriterion("eos_account <=", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountLike(String value) {
            addCriterion("eos_account like", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountNotLike(String value) {
            addCriterion("eos_account not like", value, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountIn(List<String> values) {
            addCriterion("eos_account in", values, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountNotIn(List<String> values) {
            addCriterion("eos_account not in", values, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountBetween(String value1, String value2) {
            addCriterion("eos_account between", value1, value2, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_accountNotBetween(String value1, String value2) {
            addCriterion("eos_account not between", value1, value2, "eos_account");
            return (Criteria) this;
        }

        public Criteria andEos_memoIsNull() {
            addCriterion("eos_memo is null");
            return (Criteria) this;
        }

        public Criteria andEos_memoIsNotNull() {
            addCriterion("eos_memo is not null");
            return (Criteria) this;
        }

        public Criteria andEos_memoEqualTo(String value) {
            addCriterion("eos_memo =", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoNotEqualTo(String value) {
            addCriterion("eos_memo <>", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoGreaterThan(String value) {
            addCriterion("eos_memo >", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoGreaterThanOrEqualTo(String value) {
            addCriterion("eos_memo >=", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoLessThan(String value) {
            addCriterion("eos_memo <", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoLessThanOrEqualTo(String value) {
            addCriterion("eos_memo <=", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoLike(String value) {
            addCriterion("eos_memo like", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoNotLike(String value) {
            addCriterion("eos_memo not like", value, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoIn(List<String> values) {
            addCriterion("eos_memo in", values, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoNotIn(List<String> values) {
            addCriterion("eos_memo not in", values, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoBetween(String value1, String value2) {
            addCriterion("eos_memo between", value1, value2, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andEos_memoNotBetween(String value1, String value2) {
            addCriterion("eos_memo not between", value1, value2, "eos_memo");
            return (Criteria) this;
        }

        public Criteria andTxidIsNull() {
            addCriterion("txid is null");
            return (Criteria) this;
        }

        public Criteria andTxidIsNotNull() {
            addCriterion("txid is not null");
            return (Criteria) this;
        }

        public Criteria andTxidEqualTo(String value) {
            addCriterion("txid =", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotEqualTo(String value) {
            addCriterion("txid <>", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidGreaterThan(String value) {
            addCriterion("txid >", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidGreaterThanOrEqualTo(String value) {
            addCriterion("txid >=", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLessThan(String value) {
            addCriterion("txid <", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLessThanOrEqualTo(String value) {
            addCriterion("txid <=", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidLike(String value) {
            addCriterion("txid like", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotLike(String value) {
            addCriterion("txid not like", value, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidIn(List<String> values) {
            addCriterion("txid in", values, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotIn(List<String> values) {
            addCriterion("txid not in", values, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidBetween(String value1, String value2) {
            addCriterion("txid between", value1, value2, "txid");
            return (Criteria) this;
        }

        public Criteria andTxidNotBetween(String value1, String value2) {
            addCriterion("txid not between", value1, value2, "txid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table withdraw
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}