package com.fastma.fastma.entity;

public class Withdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.req_id
     *
     * @mbggenerated
     */
    private Integer req_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.amount_token
     *
     * @mbggenerated
     */
    private Double amount_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.amount_eos
     *
     * @mbggenerated
     */
    private Double amount_eos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.if_done
     *
     * @mbggenerated
     */
    private Integer if_done;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.eos_account
     *
     * @mbggenerated
     */
    private String eos_account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.eos_memo
     *
     * @mbggenerated
     */
    private String eos_memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.txid
     *
     * @mbggenerated
     */
    private String txid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.req_id
     *
     * @return the value of withdraw.req_id
     *
     * @mbggenerated
     */
    public Integer getReq_id() {
        return req_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.req_id
     *
     * @param req_id the value for withdraw.req_id
     *
     * @mbggenerated
     */
    public void setReq_id(Integer req_id) {
        this.req_id = req_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.userid
     *
     * @return the value of withdraw.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.userid
     *
     * @param userid the value for withdraw.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.amount_token
     *
     * @return the value of withdraw.amount_token
     *
     * @mbggenerated
     */
    public Double getAmount_token() {
        return amount_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.amount_token
     *
     * @param amount_token the value for withdraw.amount_token
     *
     * @mbggenerated
     */
    public void setAmount_token(Double amount_token) {
        this.amount_token = amount_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.amount_eos
     *
     * @return the value of withdraw.amount_eos
     *
     * @mbggenerated
     */
    public Double getAmount_eos() {
        return amount_eos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.amount_eos
     *
     * @param amount_eos the value for withdraw.amount_eos
     *
     * @mbggenerated
     */
    public void setAmount_eos(Double amount_eos) {
        this.amount_eos = amount_eos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.if_done
     *
     * @return the value of withdraw.if_done
     *
     * @mbggenerated
     */
    public Integer getIf_done() {
        return if_done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.if_done
     *
     * @param if_done the value for withdraw.if_done
     *
     * @mbggenerated
     */
    public void setIf_done(Integer if_done) {
        this.if_done = if_done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.eos_account
     *
     * @return the value of withdraw.eos_account
     *
     * @mbggenerated
     */
    public String getEos_account() {
        return eos_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.eos_account
     *
     * @param eos_account the value for withdraw.eos_account
     *
     * @mbggenerated
     */
    public void setEos_account(String eos_account) {
        this.eos_account = eos_account == null ? null : eos_account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.eos_memo
     *
     * @return the value of withdraw.eos_memo
     *
     * @mbggenerated
     */
    public String getEos_memo() {
        return eos_memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.eos_memo
     *
     * @param eos_memo the value for withdraw.eos_memo
     *
     * @mbggenerated
     */
    public void setEos_memo(String eos_memo) {
        this.eos_memo = eos_memo == null ? null : eos_memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.txid
     *
     * @return the value of withdraw.txid
     *
     * @mbggenerated
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.txid
     *
     * @param txid the value for withdraw.txid
     *
     * @mbggenerated
     */
    public void setTxid(String txid) {
        this.txid = txid == null ? null : txid.trim();
    }
}